// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package scan

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[OpPlus-1]
	_ = x[OpMinus-2]
	_ = x[OpStar-3]
	_ = x[OpSlash-4]
	_ = x[OpAssign-5]
	_ = x[OpEqual-6]
	_ = x[OpNotEqual-7]
	_ = x[OpGreaterThan-8]
	_ = x[OpLessThan-9]
	_ = x[OpGeq-10]
	_ = x[OpLeq-11]
	_ = x[OpBang-12]
	_ = x[CharSemicolon-13]
	_ = x[CharLParen-14]
	_ = x[CharRParen-15]
	_ = x[CharLBrace-16]
	_ = x[CharRBrace-17]
	_ = x[KeywordTrue-18]
	_ = x[KeywordFalse-19]
	_ = x[KeywordAnd-20]
	_ = x[KeywordOr-21]
	_ = x[KeywordVar-22]
	_ = x[KeywordPrint-23]
	_ = x[KeywordIf-24]
	_ = x[KeywordElse-25]
	_ = x[KeywordWhile-26]
	_ = x[LitString-27]
	_ = x[LitNumber-28]
	_ = x[Ident-29]
	_ = x[EOF-30]
}

const _TokenType_name = "UnknownOpPlusOpMinusOpStarOpSlashOpAssignOpEqualOpNotEqualOpGreaterThanOpLessThanOpGeqOpLeqOpBangCharSemicolonCharLParenCharRParenCharLBraceCharRBraceKeywordTrueKeywordFalseKeywordAndKeywordOrKeywordVarKeywordPrintKeywordIfKeywordElseKeywordWhileLitStringLitNumberIdentEOF"

var _TokenType_index = [...]uint16{0, 7, 13, 20, 26, 33, 41, 48, 58, 71, 81, 86, 91, 97, 110, 120, 130, 140, 150, 161, 173, 183, 192, 202, 214, 223, 234, 246, 255, 264, 269, 272}

func (i TokenType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TokenType_index)-1 {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[idx]:_TokenType_index[idx+1]]
}
