/* Generated By:JavaCC: Do not edit this line. SplPrimeAutoParserConstants.java */
package splprime.autoscan;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SplPrimeAutoParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int KEYWORD_TRUE = 8;
  /** RegularExpression Id. */
  int KEYWORD_FALSE = 9;
  /** RegularExpression Id. */
  int KEYWORD_AND = 10;
  /** RegularExpression Id. */
  int KEYWORD_OR = 11;
  /** RegularExpression Id. */
  int KEYWORD_VAR = 12;
  /** RegularExpression Id. */
  int KEYWORD_PRINT = 13;
  /** RegularExpression Id. */
  int KEYWORD_IF = 14;
  /** RegularExpression Id. */
  int KEYWORD_ELSE = 15;
  /** RegularExpression Id. */
  int KEYWORD_WHILE = 16;
  /** RegularExpression Id. */
  int IDEN = 17;
  /** RegularExpression Id. */
  int LIT_NUM = 18;
  /** RegularExpression Id. */
  int LIT_STR = 19;
  /** RegularExpression Id. */
  int OP_PLUS = 20;
  /** RegularExpression Id. */
  int OP_MINUS = 21;
  /** RegularExpression Id. */
  int OP_STAR = 22;
  /** RegularExpression Id. */
  int OP_SLASH = 23;
  /** RegularExpression Id. */
  int OP_ASSIGN = 24;
  /** RegularExpression Id. */
  int OP_EQUAL = 25;
  /** RegularExpression Id. */
  int OP_NOT_EQUAL = 26;
  /** RegularExpression Id. */
  int OP_GREATER_THAN = 27;
  /** RegularExpression Id. */
  int OP_LESS_THAN = 28;
  /** RegularExpression Id. */
  int OP_GEQ = 29;
  /** RegularExpression Id. */
  int OP_LEQ = 30;
  /** RegularExpression Id. */
  int OP_BANG = 31;
  /** RegularExpression Id. */
  int CHAR_SEMICOLON = 32;
  /** RegularExpression Id. */
  int CHAR_LPAREN = 33;
  /** RegularExpression Id. */
  int CHAR_RPAREN = 34;
  /** RegularExpression Id. */
  int CHAR_LBRACE = 35;
  /** RegularExpression Id. */
  int CHAR_RBRACE = 36;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int WithinComment = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"//\"",
    "\"\\n\"",
    "<token of kind 3>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"true\"",
    "\"false\"",
    "\"and\"",
    "\"or\"",
    "\"var\"",
    "\"print\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "<IDEN>",
    "<LIT_NUM>",
    "<LIT_STR>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"=\"",
    "\"==\"",
    "\"!=\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"!\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
  };

}
