/* Generated By:JavaCC: Do not edit this line. SplPrimeAutoConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SplPrimeAutoConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IDEN = 7;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int WithinComment = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"//\"",
    "\"\\n\"",
    "<token of kind 3>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "<IDEN>",
  };

}
